DROP TABLE IF EXISTS quotations;
CREATE TABLE IF NOT EXISTS quotations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code_out TEXT NOT NULL,
  code_in TEXT NOT NULL,
  bid REAL NOT NULL,
  timestamp INTEGER NOT NULL
);